"use client";

import { useState, useMemo, useCallback, useEffect } from "react";
import Link from "next/link";
import { MOCK_PATTERNS, MOCK_MANUAL_BUNDLES } from "@/lib/mock-data";
import { getPatterns, getManualInput, getPattern } from "@/lib/api";
import type { DumpPatternSummary, DumpPatternResponse, ManualInputBundle } from "@/lib/types";
import LifecycleBadge from "@/components/LifecycleBadge";
import DumpTypeBadge from "@/components/DumpTypeBadge";
import ConfidenceBar from "@/components/ConfidenceBar";
import ManualInputModal from "@/components/ManualInputModal";
import { useMyAirports } from "@/lib/useMyAirports";

const TIER_LABELS: Record<number, string> = {
  1: "Daily",
  2: "Weekly",
  3: "Monthly",
};

type ViewMode = "my" | "all";

/** Build a pre-validation bundle from raw pattern data (no ITA run yet). */
function buildPreValidationBundle(p: DumpPatternResponse): ManualInputBundle {
  const via = p.routing_points.length > 0 ? ` via ${p.routing_points.join(", ")}` : "";
  const uniqueCarriers = Array.from(new Set([p.ticketing_carrier_iata, ...p.operating_carriers]));
  const carriers = uniqueCarriers.join("/");

  // Human description based on dump type
  const description =
    p.dump_type === "TP_DUMP"
      ? `Ticketing point dump — ${p.ticketing_carrier_iata} metal, ${p.origin_iata}→${p.destination_iata}${via}`
      : p.dump_type === "CARRIER_SWITCH"
      ? `Carrier switch dump — book on ${p.ticketing_carrier_iata}, operating: ${carriers}`
      : p.dump_type === "FARE_BASIS"
      ? `Fare basis dump on ${p.ticketing_carrier_iata}${p.fare_basis_hint ? ` (${p.fare_basis_hint})` : ""}`
      : `Alliance rule dump — ${carriers}${via}`;

  // If this pattern has multi_city_segments, use the scan engine view
  if (p.multi_city_segments && p.multi_city_segments.length > 0) {
    return {
      routing_code_string: p.optimized_routing ?? p.ita_routing_code ?? "",
      human_description: description,
      ita_matrix_steps: [], // generated by ScanEngineView from multi_city_segments
      expected_yq_savings_usd: p.expected_yq_savings_usd ?? 0,
      expected_yq_carrier: p.ticketing_carrier_iata,
      validation_timestamp: p.created_at,
      confidence_score: p.confidence_score,
      backup_routing_code: null,
      notes: "Scanner-generated pattern — not yet machine-validated. Run both ITA Matrix queries and compare prices manually.",
      // Scan engine fields
      multi_city_segments: p.multi_city_segments,
      dump_segment: p.dump_segment,
      baseline_routing: p.baseline_routing,
      optimized_routing: p.optimized_routing,
      is_scan_engine_bundle: true,
    };
  }

  // Fallback: legacy single-routing-code pattern
  const steps = [
    `Go to matrix.itasoftware.com`,
    `Set origin to ${p.origin_iata} and destination to ${p.destination_iata}`,
    `Open "Routing codes" and paste the routing code below`,
    `Set cabin class and dates, then click Search`,
    `In results, verify YQ surcharge shows $0 in the fare breakdown`,
    p.fare_basis_hint ? `Look for fare basis code ${p.fare_basis_hint} in the fare details` : null,
    `Note: This pattern has not yet been machine-validated — confirm manually`,
  ].filter(Boolean) as string[];

  return {
    routing_code_string: p.ita_routing_code ?? "",
    human_description: description,
    ita_matrix_steps: steps,
    expected_yq_savings_usd: p.expected_yq_savings_usd ?? 0,
    expected_yq_carrier: p.ticketing_carrier_iata,
    validation_timestamp: p.created_at,
    confidence_score: p.confidence_score,
    backup_routing_code: null,
    notes: "Community-sourced routing — not yet machine-validated. Verify YQ savings manually before booking.",
  };
}

export default function PatternsPage() {
  const [viewMode, setViewMode] = useState<ViewMode>("my");
  const [origin, setOrigin] = useState("");
  const [destination, setDestination] = useState("");
  const [dumpType, setDumpType] = useState("");
  const [carrier, setCarrier] = useState("");
  const [minSavings, setMinSavings] = useState("");
  const [modalBundle, setModalBundle] = useState<{
    bundle: ManualInputBundle;
    route: string;
  } | null>(null);
  const [editingAirports, setEditingAirports] = useState(false);
  const [newCode, setNewCode] = useState("");

  const { airports, add, remove, reset } = useMyAirports();
  const [patterns, setPatterns] = useState<DumpPatternSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [usingMock, setUsingMock] = useState(false);

  useEffect(() => {
    getPatterns({ page_size: 100 })
      .then((res) => {
        if (res.items.length > 0) {
          setPatterns(res.items);
        } else {
          // No real data yet — fall back to mock for UI demo
          setPatterns(MOCK_PATTERNS);
          setUsingMock(true);
        }
      })
      .catch(() => {
        setPatterns(MOCK_PATTERNS);
        setUsingMock(true);
      })
      .finally(() => setLoading(false));
  }, []);

  const openManualInput = useCallback(async (pattern: DumpPatternSummary) => {
    if (usingMock) {
      const bundle = MOCK_MANUAL_BUNDLES[pattern.id];
      if (bundle) {
        setModalBundle({
          bundle,
          route: `${pattern.origin_iata} \u2192 ${pattern.destination_iata}`,
        });
      }
      return;
    }
    const route = `${pattern.origin_iata} \u2192 ${pattern.destination_iata}`;
    try {
      // Try the fully validated bundle first
      const bundle = await getManualInput(pattern.id);
      setModalBundle({ bundle, route });
    } catch {
      // No validated bundle yet — fetch full pattern and build a pre-validation bundle
      try {
        const full = await getPattern(pattern.id);
        setModalBundle({ bundle: buildPreValidationBundle(full), route });
      } catch {
        // silently fail if pattern detail also unavailable
      }
    }
  }, [usingMock]);

  const filtered = useMemo(() => {
    let result = [...patterns];

    // Apply My Airports filter
    if (viewMode === "my") {
      result = result.filter(
        (p) =>
          airports.includes(p.origin_iata) ||
          airports.includes(p.destination_iata)
      );
    }

    if (origin) result = result.filter((p) => p.origin_iata.includes(origin.toUpperCase()));
    if (destination) result = result.filter((p) => p.destination_iata.includes(destination.toUpperCase()));
    if (dumpType) result = result.filter((p) => p.dump_type === dumpType);
    if (carrier) result = result.filter((p) => p.ticketing_carrier_iata.includes(carrier.toUpperCase()));
    if (minSavings) {
      const min = parseFloat(minSavings);
      if (!isNaN(min)) result = result.filter((p) => (p.expected_yq_savings_usd ?? 0) >= min);
    }
    return result.sort((a, b) => (b.expected_yq_savings_usd ?? 0) - (a.expected_yq_savings_usd ?? 0));
  }, [patterns, viewMode, airports, origin, destination, dumpType, carrier, minSavings]);

  const hasFilters = origin || destination || dumpType || carrier || minSavings;

  if (loading) {
    return (
      <div className="animate-fade-in flex items-center justify-center py-20">
        <span className="text-[14px] text-[#5f6368]">Loading patterns...</span>
      </div>
    );
  }

  const handleAddCode = () => {
    const code = newCode.toUpperCase().trim();
    if (code.length === 3) {
      add(code);
      setNewCode("");
    }
  };

  return (
    <div className="animate-fade-in">
      {/* Mock data banner */}
      {usingMock && (
        <div className="mb-4 px-4 py-2.5 bg-[#fef7e0] border border-[#f9d67a] rounded-lg text-[13px] text-[#5f6368]">
          Showing demo data — no validated patterns in the database yet. Run the ingestion pipeline to discover real fuel dump patterns.
        </div>
      )}

      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div>
          <h1 className="text-[22px] font-normal text-[#202124]">
            Fuel Dump Patterns
          </h1>
          <p className="text-[13px] text-[#5f6368] mt-1">
            {filtered.length} active pattern{filtered.length !== 1 ? "s" : ""} sorted by YQ savings
          </p>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-[12px] text-[#80868b]">
            {patterns.length} total
          </span>
        </div>
      </div>

      {/* View toggle: My Airports / All Patterns */}
      <div className="flex items-center gap-3 mb-4">
        <div className="flex items-center gap-1 bg-[#f1f3f4] rounded-lg p-0.5">
          <button
            onClick={() => setViewMode("my")}
            className={`px-3 py-1.5 text-[12px] font-medium rounded-md transition-colors ${
              viewMode === "my"
                ? "bg-white text-[#202124] shadow-sm"
                : "text-[#5f6368] hover:text-[#202124]"
            }`}
          >
            My Airports
          </button>
          <button
            onClick={() => setViewMode("all")}
            className={`px-3 py-1.5 text-[12px] font-medium rounded-md transition-colors ${
              viewMode === "all"
                ? "bg-white text-[#202124] shadow-sm"
                : "text-[#5f6368] hover:text-[#202124]"
            }`}
          >
            All Patterns
          </button>
        </div>
        {viewMode === "my" && (
          <button
            onClick={() => setEditingAirports(!editingAirports)}
            className="text-[12px] text-[#1a73e8] hover:text-[#1557b0] font-medium"
          >
            {editingAirports ? "Done" : "Edit airports"}
          </button>
        )}
      </div>

      {/* My Airports editor */}
      {viewMode === "my" && editingAirports && (
        <div className="mb-4 p-4 bg-[#f8f9fa] border border-[#dadce0] rounded-lg">
          <div className="flex items-center justify-between mb-3">
            <span className="text-[13px] font-medium text-[#202124]">
              My Airports ({airports.length})
            </span>
            <button
              onClick={reset}
              className="text-[11px] text-[#5f6368] hover:text-[#202124]"
            >
              Reset to defaults
            </button>
          </div>
          <div className="flex flex-wrap gap-1.5 mb-3">
            {airports.map((code) => (
              <span
                key={code}
                className="inline-flex items-center gap-1 px-2.5 py-1 bg-white border border-[#dadce0] rounded-md text-[12px] font-medium text-[#202124]"
              >
                {code}
                <button
                  onClick={() => remove(code)}
                  className="ml-0.5 text-[#80868b] hover:text-[#c5221f] transition-colors"
                >
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </button>
              </span>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <input
              type="text"
              placeholder="Add IATA code"
              value={newCode}
              onChange={(e) => setNewCode(e.target.value.toUpperCase().slice(0, 3))}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleAddCode();
              }}
              className="h-8 w-24 px-2.5 text-[12px] border border-[#dadce0] rounded-md bg-white text-[#202124] placeholder:text-[#80868b] focus:outline-none focus:border-[#1a73e8] focus:ring-1 focus:ring-[#1a73e8] uppercase"
            />
            <button
              onClick={handleAddCode}
              disabled={newCode.trim().length !== 3}
              className="h-8 px-3 text-[12px] font-medium bg-[#1a73e8] text-white rounded-md hover:bg-[#1557b0] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
            >
              Add
            </button>
          </div>
        </div>
      )}

      {/* My Airports chips (when not editing) */}
      {viewMode === "my" && !editingAirports && airports.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-4">
          {airports.map((code) => (
            <span
              key={code}
              className="px-2 py-0.5 bg-[#e8f0fe] text-[#1a73e8] rounded text-[11px] font-medium"
            >
              {code}
            </span>
          ))}
        </div>
      )}

      {/* Filters */}
      <div className="flex items-center gap-3 mb-5 flex-wrap">
        <FilterInput placeholder="Origin" value={origin} onChange={setOrigin} width="w-20" />
        <FilterInput placeholder="Dest" value={destination} onChange={setDestination} width="w-20" />
        <select
          value={dumpType}
          onChange={(e) => setDumpType(e.target.value)}
          className="h-9 px-3 text-[13px] border border-[#dadce0] rounded-lg bg-white text-[#202124] focus:outline-none focus:border-[#1a73e8] focus:ring-1 focus:ring-[#1a73e8]"
        >
          <option value="">All types</option>
          <option value="TP_DUMP">TP Dump</option>
          <option value="CARRIER_SWITCH">Carrier Switch</option>
          <option value="FARE_BASIS">Fare Basis</option>
          <option value="ALLIANCE_RULE">Alliance Rule</option>
        </select>
        <FilterInput placeholder="Carrier" value={carrier} onChange={setCarrier} width="w-20" />
        <FilterInput placeholder="Min $" value={minSavings} onChange={setMinSavings} width="w-20" />
        {hasFilters && (
          <button
            onClick={() => { setOrigin(""); setDestination(""); setDumpType(""); setCarrier(""); setMinSavings(""); }}
            className="text-[12px] text-[#1a73e8] hover:text-[#1557b0] font-medium"
          >
            Clear
          </button>
        )}
      </div>

      {/* Table */}
      <div className="border border-[#dadce0] rounded-lg overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="bg-[#f8f9fa] border-b border-[#dadce0]">
              <th className="text-left px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">Route</th>
              <th className="text-left px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">Type</th>
              <th className="text-left px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">Carrier</th>
              <th className="text-right px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">YQ Savings</th>
              <th className="text-left px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">Confidence</th>
              <th className="text-left px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">Freshness</th>
              <th className="text-left px-4 py-3 text-[11px] font-medium text-[#5f6368] uppercase tracking-wider">State</th>
              <th className="px-4 py-3"></th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#e8eaed]">
            {filtered.map((pattern) => (
              <PatternRow key={pattern.id} pattern={pattern} onGetManualInput={openManualInput} />
            ))}
            {filtered.length === 0 && (
              <tr>
                <td colSpan={8} className="px-4 py-12 text-center text-[14px] text-[#5f6368]">
                  {viewMode === "my"
                    ? "No patterns match your airports — try editing your list or switching to All Patterns"
                    : "No patterns match your filters"}
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {modalBundle && (
        <ManualInputModal
          bundle={modalBundle.bundle}
          route={modalBundle.route}
          onClose={() => setModalBundle(null)}
        />
      )}
    </div>
  );
}

function PatternRow({
  pattern,
  onGetManualInput,
}: {
  pattern: DumpPatternSummary;
  onGetManualInput: (p: DumpPatternSummary) => void;
}) {
  const via = pattern.routing_points.length > 0
    ? ` via ${pattern.routing_points.join(", ")}`
    : "";

  return (
    <tr className="hover:bg-[#f8f9fa] transition-colors group">
      <td className="px-4 py-3">
        <Link href={`/patterns/${pattern.id}`} className="group-hover:text-[#1a73e8]">
          <span className="text-[14px] font-medium text-[#202124]">
            {pattern.origin_iata}
          </span>
          <span className="text-[14px] text-[#5f6368] mx-1.5">&rarr;</span>
          <span className="text-[14px] font-medium text-[#202124]">
            {pattern.destination_iata}
          </span>
          {via && (
            <span className="text-[11px] text-[#80868b] ml-1.5">{via}</span>
          )}
        </Link>
      </td>
      <td className="px-4 py-3">
        <DumpTypeBadge type={pattern.dump_type} />
      </td>
      <td className="px-4 py-3">
        <span className="text-[13px] text-[#202124] font-medium">
          {pattern.ticketing_carrier_iata}
        </span>
        {pattern.operating_carriers.length > 1 && (
          <span className="text-[11px] text-[#80868b] ml-1">
            +{pattern.operating_carriers.length - 1}
          </span>
        )}
      </td>
      <td className="px-4 py-3 text-right">
        <span className="text-[16px] font-semibold text-[#0d904f] tabular-nums">
          ${pattern.expected_yq_savings_usd?.toFixed(0) ?? "—"}
        </span>
      </td>
      <td className="px-4 py-3">
        <ConfidenceBar score={pattern.confidence_score} />
      </td>
      <td className="px-4 py-3">
        <span className="text-[12px] text-[#5f6368]">
          {TIER_LABELS[pattern.freshness_tier] ?? "—"}
        </span>
      </td>
      <td className="px-4 py-3">
        <LifecycleBadge state={pattern.lifecycle_state} />
      </td>
      <td className="px-4 py-3">
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
          <button
            onClick={(e) => { e.stopPropagation(); onGetManualInput(pattern); }}
            className="inline-flex items-center gap-1 px-3 py-1.5 text-[12px] font-medium bg-[#1a73e8] text-white hover:bg-[#1557b0] rounded-md transition-colors"
          >
            Get Manual Input
          </button>
          <Link
            href={`/patterns/${pattern.id}`}
            className="inline-flex items-center gap-1 px-2 py-1.5 text-[12px] font-medium text-[#5f6368] hover:bg-[#f1f3f4] rounded-md transition-colors"
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="9 18 15 12 9 6" />
            </svg>
          </Link>
        </div>
      </td>
    </tr>
  );
}

function FilterInput({
  placeholder,
  value,
  onChange,
  width,
}: {
  placeholder: string;
  value: string;
  onChange: (v: string) => void;
  width: string;
}) {
  return (
    <input
      type="text"
      placeholder={placeholder}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      className={`h-9 px-3 text-[13px] border border-[#dadce0] rounded-lg bg-white text-[#202124] placeholder:text-[#80868b] focus:outline-none focus:border-[#1a73e8] focus:ring-1 focus:ring-[#1a73e8] ${width}`}
    />
  );
}
